 
 
import Head from 'next/head'
import { useState } from 'react';
import SigninForm from './SigninForm';
import RegisterForm from './RegisterForm';
import { BiUserPlus } from "react-icons/bi";
 
export default function Home() {


const [visible,setvisible] = useState(false);

 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-14 container mx-auto h-screen flex items-center justify-center"> 
       <div className="  mx-auto max-w-3xl  py-10 flex    ">
       <RegisterForm></RegisterForm>  
       </div> 
      </main>
    </>
  )
}
